all:
  children:
    debian:
      hosts:
        deb_11_1:
          ansible_host: 192.168.56.102
    ubuntu:
      hosts:
        ubu_18_1:
          ansible_host: 192.168.56.101
        ubu_20_1:
          ansible_host: 192.168.56.103